# Generated by Django 5.0.1 on 2024-01-31 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
    ]
